SELECT TRUNCATE(a.PRICE,-4) AS PRICE_GROUP, /* TRUNCATE(숫자,버릴 자릿수)  표현하는 방식 ex) TRUNCATE(1234.56789,-2)==1200 */
       COUNT(a.PRODUCT_ID) AS PRODUCTS
  FROM PRODUCT a
 GROUP BY PRICE_GROUP
 ORDER BY PRICE_GROUP