SELECT a.PRODUCT_CODE,
       SUM(a.PRICE * b.SALES_AMOUNT) as SALES
  FROM PRODUCT a JOIN OFFLINE_SALE b
    ON a.PRODUCT_ID=b.PRODUCT_ID
    GROUP BY a.PRODUCT_CODE
    ORDER by SALES DESC, a.PRODUCT_CODE asc;