  SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, 
         COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
  FROM ANIMAL_OUTS
  GROUP BY HOUR /* 시간을 나타내는 쿼리 */
  HAVING HOUR BETWEEN 9 AND 19
  ORDER BY HOUR ASC;